# Generated by Django 5.2.4 on 2025-07-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handloom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
